<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ReservationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('reservations')->truncate(); // Ya eu des problèmes du coup on vide la table avant de la remplir au cas où

        DB::table('reservations')->insert([
            [
                'nom_client' => 'Alice',
                'email_client' => 'alice@example.com',
                'tel_client' => '0612345678',
                'jeu_client' => 'The Legend of Zelda: Breath of the Wild',
                'plateforme_client' => 'Switch',
                'reservation_date' => '2025-05-10',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Bob',
                'email_client' => 'bob@example.com',
                'tel_client' => '0687654321',
                'jeu_client' => 'Super Mario Odyssey',
                'plateforme_client' => 'Switch',
                'reservation_date' => '2025-04-15',
                'status' => 'Confirmée',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Clairezeee',
                'email_client' => 'claire@example.com',
                'tel_client' => '0698745432',
                'jeu_client' => 'God of War',
                'plateforme_client' => 'PS4',
                'reservation_date' => '2025-03-20',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'David',
                'email_client' => 'david@example.com',
                'tel_client' => '0600000001',
                'jeu_client' => 'Horizon Forbidden West',
                'plateforme_client' => 'PS5',
                'reservation_date' => '2025-06-01',
                'status' => 'Annulée',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Liam',
                'email_client' => 'liam@example.com',
                'tel_client' => '0600000003',
                'jeu_client' => 'Red Dead Redemption 2',
                'plateforme_client' => 'PS4',
                'reservation_date' => '2025-06-03',
                'status' => 'Confirmée',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Olivia',
                'email_client' => 'olivia@example.com',
                'tel_client' => '0600000004',
                'jeu_client' => 'Final Fantasy VII Remake',
                'plateforme_client' => 'PS4',
                'reservation_date' => '2025-06-04',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Noah',
                'email_client' => 'noah@example.com',
                'tel_client' => '0600000005',
                'jeu_client' => 'Minecraft',
                'plateforme_client' => 'PC',
                'reservation_date' => '2025-06-05',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Emma',
                'email_client' => 'emma2@example.com',
                'tel_client' => '0600000006',
                'jeu_client' => 'Fortnite',
                'plateforme_client' => 'PC',
                'reservation_date' => '2025-06-06',
                'status' => 'Confirmée',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Mia',
                'email_client' => 'mia@example.com',
                'tel_client' => '0600000007',
                'jeu_client' => 'Cyberpunk 2077',
                'plateforme_client' => 'PC',
                'reservation_date' => '2025-06-07',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Lucas',
                'email_client' => 'lucas@example.com',
                'tel_client' => '0600000008',
                'jeu_client' => 'The Witcher 3: Wild Hunt',
                'plateforme_client' => 'PC',
                'reservation_date' => '2025-06-08',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Chloe',
                'email_client' => 'chloe@example.com',
                'tel_client' => '0600000009',
                'jeu_client' => 'Animal Crossing: New Horizons',
                'plateforme_client' => 'Switch',
                'reservation_date' => '2025-06-09',
                'status' => 'Confirmée',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Elijah',
                'email_client' => 'elijah@example.com',
                'tel_client' => '0600000010',
                'jeu_client' => "Assassin's Creed Valhalla",
                'plateforme_client' => 'PS5',
                'reservation_date' => '2025-06-10',
                'status' => 'Confirmée',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Sophie',
                'email_client' => 'sophie@example.com',
                'tel_client' => '0600000011',
                'jeu_client' => 'Resident Evil Village',
                'plateforme_client' => 'PS5',
                'reservation_date' => '2025-06-11',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'James',
                'email_client' => 'james@example.com',
                'tel_client' => '0600000012',
                'jeu_client' => 'FIFA 23',
                'plateforme_client' => 'PS5',
                'reservation_date' => '2025-06-12',
                'status' => 'Confirmée',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom_client' => 'Jules VINET LATRILLE',
                'email_client' => 'julesvinet64@gmail.com',
                'tel_client' => '0607845150',
                'jeu_client' => 'Cyberpunk 2077',
                'plateforme_client' => 'PC',
                'reservation_date' => '2005-09-20',
                'status' => 'En attente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
